spring.application.name=media-monolith
app.storage.local.path=/home/pavlev/media/monolith

spring.datasource.url=jdbc:postgresql://localhost:5432/media_monolith
spring.datasource.username=admin
spring.datasource.password=admin
spring.jpa.hibernate.ddl-auto=update
