spring.application.name=media-monolith
app.storage.local.path=/home/pavlev/media/monolith

spring.servlet.multipart.max-file-size=500MB
spring.servlet.multipart.max-request-size=500MB

spring.datasource.url=jdbc:postgresql://localhost:5433/media_monolith
spring.datasource.username=admin
spring.datasource.password=admin
spring.jpa.hibernate.ddl-auto=update
